/*  hlsmodule.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include<linux/fs.h>
#include<linux/string.h>
#include<linux/uaccess.h>
#include<linux/device.h>
#include<linux/cdev.h>
#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("hlsmodule - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "hlsmodule"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */


#define CLASS_NAME "CLASS_TUT"
static char ker_buf[100];
  
static char math_operation;
static int operand_1 =0;
static int operand_2 =0;
static int result =0;
static int resp_ready =0;
static struct class *driver_class=NULL;
static dev_t first;
static struct cdev c_dev;
static struct device *ourDevice;
volatile unsigned int *regA;
volatile unsigned int *regB;
volatile unsigned int *regOp;
volatile unsigned int *regC;
volatile unsigned int *regCrtl;



struct hlsmodule_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};



//character call back
static int dev_open(struct inode *inod,struct file *fil);
static ssize_t dev_read(struct file *filep,char *buf,size_t len,loff_t *off);
static ssize_t dev_write(struct file *filep,char *buf,size_t len,loff_t *off);
static int dev_release(struct inode *inod ,struct file *fil);

void ipStart(void){
   unsigned int data =(*regCrtl & 0x80);
   *regCrtl=(data | 0x01);
}
unsigned int ipIsDone(void){
   unsigned int data = *regCrtl;
   return ((data >> 1) & 0x1);
} 

/*
//control the execution of IP
static ssize_t writeSomeAttr(struct device *dev ,struct device_attribute *attr,const char *buf,size_t count) {
   printk(KERN_ALERT "Received %d bytes atributes %s \n",(int)count,buf);
   if(count>0){
      if(buf[0]=='=') {
         printk(KERN_ALERT "calculate some op1:%d op2 :%d operation :%c \n",operand_1,operand_2,math_operation);
         resp_ready = 1;
         switch (math_operation) {
            case '+': {
               *regOp=0;
               break;
            }
            case '-': {
               *regOp=1;
               break;
            }
            
            case '*': {
               *regOp=2;
               break;
            }
            case '/': {
               *regOp=3;
               break;
            }
            default:
               *regOp=0;
         }
         printk(KERN_ALERT "Start IP Core\n");
         ipStart();
         while(!ipIsDone());
         printk(KERN_ALERT "IP Core is done\n");
         result=*regC;
         printk(KERN_ALERT "Result is %d \n",*regC);
      }
   }
   return count;
}

static ssize_t readSomeAttr(struct device *dev,struct device_attribute *attr, char *buf) {
   int isBusyResp=0;
   sprintf(buf,"Busy is :%d\n",isBusyResp);
   return strlen(buf)+1;
}

static DEVICE_ATTR(parCrtl,S_IWUSR,NULL,writeSomeAttr);
static DEVICE_ATTR(isBusy,S_IRUGO,readSomeAttr,NULL);
*/

static struct file_operations f_ops={
             .read=dev_read,
             .write=dev_write,
             .open=dev_open,
             .release=dev_release,
}; 


static irqreturn_t hlsmodule_irq(int irq, void *lp)
{
	printk("hlsmodule interrupt\n");
	return IRQ_HANDLED;
}

static int hlsmodule_probe(struct platform_device *pdev) {

	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct hlsmodule_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct hlsmodule_local *) kmalloc(sizeof(struct hlsmodule_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate hlsmodule device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "hlsmodule: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}
//normal device driver

        if(alloc_chrdev_region(&first,0,1,"Leonardo") < 0){
           printk(KERN_ALERT "alloc chrdev region failed\n");
           return -1;
        }

//Create class(/sysfs)
         driver_class=class_create(THIS_MODULE,CLASS_NAME);
         if(driver_class == NULL){
         printk(KERN_ALERT "Create class failed\n");
         class_destroy(driver_class);
         unregister_chrdev_region(first,1);

         return -1;
         }


         if(device_create(driver_class,NULL,first,NULL,"tutDevice") == NULL){
         printk(KERN_ALERT "Create device failed\n");
         device_destroy(driver_class,first);
         class_destroy(driver_class);
         unregister_chrdev_region(first,1);
         return -1;
         }
         
         cdev_init(&c_dev,&f_ops);
         if(cdev_add(&c_dev,first,1)==-1){
            printk(KERN_ALERT "Create character device failed\n");
            device_destroy(driver_class,first);
            class_destroy(driver_class);
            unregister_chrdev_region(first,1);
            return -1;
         }
         
  /*       if(device_create_file(ourDevice,&dev_attr_parCrtl) < 0){
            printk(KERN_ALERT "Attribute device creation failed\n");
            return -1;
         } else {
            printk("parCrtl created\n");
         }

         if(device_create_file(ourDevice,&dev_attr_isBusy) < 0) {
            printk(KERN_ALERT "Attribute device creation failed\n");
            return -1;
         } else {
            printk("isBusy class attribute created\n");
         }
*/
	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "hlsmodule at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
                //configuring for pointers

                regA=(unsigned int __force)lp->base_addr + 0x10;
                regB=(unsigned int __force)lp->base_addr + 0x18;
                regOp=(unsigned int __force)lp->base_addr + 0x20;
                regC=(unsigned int __force)lp->base_addr + 0x28;
                regCrtl=(unsigned int __force)lp->base_addr + 0x00;
                printk("regA:0x%08x\n",(unsigned int)regA);
                printk("regB:0x%08x\n",(unsigned int)regB);
                printk("regOp:0x%08x\n",(unsigned int)regOp);
                printk("regC:0x%08x\n",(unsigned int)regC);
                printk("regCrtl:0x%08x\n",(unsigned int)regCrtl);
		return 0;
	}

/*	//lp->irq = r_irq->start;
	//rc = request_irq(lp->irq, &hlsmodule_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}*/

	dev_info(dev,"hlsmodule at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
/*
error3:
	free_irq(lp->irq, lp);*/
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int hlsmodule_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct hlsmodule_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id hlsmodule_of_match[] = {
	{ .compatible = "xlnx,simpleAlu-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, hlsmodule_of_match);
#else
# define hlsmodule_of_match
#endif


static struct platform_driver hlsmodule_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= hlsmodule_of_match,
	},
	.probe		= hlsmodule_probe,
	.remove		= hlsmodule_remove,
};

static int __init hlsmodule_init(void)
{
	printk("<1>saif module world.\n");
//	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
//	       mystr);

	return platform_driver_register(&hlsmodule_driver);
}


static void __exit hlsmodule_exit(void)
{
	platform_driver_unregister(&hlsmodule_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}


static int dev_open(struct inode *inod,struct file *fil){
         printk(KERN_INFO  "device opened\n");
         return 0;
}

//character device file is written
static ssize_t dev_write(struct file *filep,char *buf,size_t len,loff_t *off){
   copy_from_user(ker_buf,buf,len);
   sscanf(ker_buf,"%d,%d,%c",&operand_1,&operand_2,&math_operation);
   ker_buf[len]=0;
   //changr ip registers
   *regA = (unsigned int)operand_1;
   *regB = (unsigned int)operand_2;
// Print len - kkk
   printk(KERN_ALERT "receiving math operation <%d %c %d>\n",operand_1,math_operation,operand_2);
   printk(KERN_ALERT "len inside write is %d\n",len);


   printk(KERN_ALERT "****************Extra from atributes****************** \n");

   //printk(KERN_ALERT "\nReceived %d bytes atributes %s \n",(int)len,buf);
   if(len>0){
       
         printk(KERN_ALERT "calculate some op1:%d op2 :%d operation :%c \n",operand_1,operand_2,math_operation);
         resp_ready = 1;
         switch (math_operation) {
            case '+': {
               *regOp=0;
               break;
            }
            case '-': {
               *regOp=1;
               break;
            }
            
            case '*': {
               *regOp=2;
               break;
            }
            case '/': {
               *regOp=3;
               break;
            }
            default:
               *regOp=0;
         }
// Print *a, *b, *ctrl
// print a,b,ctrl
         printk(KERN_ALERT "regOp:%d \n",*regOp);
         printk(KERN_ALERT "Start IP Core\n");
         ipStart();
         while(!ipIsDone());
         printk(KERN_ALERT "IP Core is done\n");
         result=*regC;
         printk(KERN_ALERT "Result is %d \n",*regC);
      
   }

   printk(KERN_ALERT "****************Extra from atributes****************** \n\n");



   return len;
   }

//character device file is read
static ssize_t dev_read(struct file *filep,char *buf,size_t len,loff_t *off) {
   if(resp_ready) {
      resp_ready=0;
      // print len - kkk
      printk(KERN_ALERT "reading device rx: %d\n",(int)len);
      int n = sprintf(ker_buf,"%d\n",result);
      copy_to_user(buf,ker_buf,n);
      printk(KERN_ALERT "returning %s rx: %d\n",ker_buf,n);
      printk(KERN_ALERT "len inside read is %d\n",len);
      return n;
   } else {
      printk(KERN_ALERT "resp_ready is %d \n", resp_ready);
   }
   return 0;
}

static int dev_release(struct inode *inod ,struct file *fil){
    printk(KERN_ALERT "device closed\n");
    return 0;
}


module_init(hlsmodule_init);
module_exit(hlsmodule_exit);


